- name: Configure webserver with nginx
  hosts: centos1
  become: True
  
  tasks:
    
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Set up nginx config directory
    file:
      path: "{{ item.path }}"
      state: "{{ item.state }}"
      owner: root
      group: root
      mode: 0777
    with_items:
      - { path: '/etc/nginx/sites-available/default', state: 'directory'}
      - { path: '/etc/nginx/sites-enabled', state: 'directory'}

  - name: Copy nginx config file
    copy: 
      owner: root
      group: root
      src: files/nginx.conf 
      dest: /etc/nginx/sites-available/default

  - name: Enable configuration
    file:
      src: /etc/nginx/sites-available/default 
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: Insert Index Page
    template:
      src: templates/index.html
      dest: /usr/share/nginx/html/index.html mode=0644

  - name: Start NGiNX
    service:
      name: nginx
      state: started

